name: 🐞 Bug report
description: Create a report to help us improve (use this to report bugs only).
title: "[BUG] <title>"
labels: [🐞 bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is. Include images if relevant.
    placeholder: A bug happened!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: | 
    Steps to reproduce the bug.

    Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: dropdown
  id: browsers
  attributes:
    lablel: Browser
    description: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Chrome
      - Firefox
      - Opera
      - Microsoft Edge
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false