name: ⚡ Feature request
description: Request a feature you'd like to see in lightning!
title: "[Feature] <title>"
labels: [idea]
body:
  - type: markdown
    attributes:
      value: |
        We're always looking for suggestions on how we could improve lightning!
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is. Include images / mockups if relevant.
      placeholder: I want lightning to able to...
      required: true