name: Build Production

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    name: build-prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install
      
      - name: Build production
        run: yarn build

      - name: Archive firefox production zip file
        uses: actions/upload-artifact@v2
        with:
          name: firefox.xpi
          path: dist/production/firefox.xpi

      - name: Archive chrome production zip file
        uses: actions/upload-artifact@v2
        with:
          name: chrome.zip
          path: dist/production/chrome.zip

      - name: Archive opera production zip file
        uses: actions/upload-artifact@v2
        with:
          name: opera.crx
          path: dist/production/opera.crx
